#!/bin/bash

REMOTE=$(git config --get remote.origin.url)

mkdir dist
npm run build
cp *.html *.css *.js *.png *.gif dist
cd dist
git init
git remote add origin $REMOTE
git checkout -b gh-pages
git add ./*
git commit -m 'Publish preso'
git push --force origin gh-pages
cd ..
rm -rf dist
